AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Swift API

Resources:
    RestApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod

    ApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: bootstrap
            Runtime: provided.al2
            CodeUri: .
            MemorySize: 128
            Timeout: 30
            Architectures:
              - arm64
            Events:
                RootEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref RestApi
                        Path: /
                        Method: any
                        Auth:
                            ApiKeyRequired: true
                ProxyEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref RestApi
                        Path: /{proxy+}
                        Method: any
                        Auth:
                            ApiKeyRequired: true

    ApiKey:
        Type: AWS::ApiGateway::ApiKey
        DependsOn:
        - RestApi
        - RestApiProdStage
        - ApiFunction
        Properties:
            Name: !Join ["", [{"Ref": "AWS::StackName"}, "-apikey-", !Select [2, !Split ['/', !Ref AWS::StackId]]]]
            Description: "API Key"
            Enabled: true
            StageKeys:
                - RestApiId: !Ref RestApi
                  StageName: Prod

    ApiUsagePlan:
        Type: AWS::ApiGateway::UsagePlan
        DependsOn:
        - RestApi
        - RestApiProdStage
        - ApiFunction
        Properties:
            ApiStages:
                - ApiId: !Ref RestApi
                  Stage: Prod
            Description: !Join [" ", [{"Ref": "AWS::StackName"}, "usage plan"]]
            Quota:
                Limit: 1000
                Period: DAY
            UsagePlanName: !Join ["", [{"Ref": "AWS::StackName"}, "-usage-plan"]]

    ApiUsagePlanKey:
        Type: AWS::ApiGateway::UsagePlanKey
        DependsOn:
        - RestApi
        - RestApiProdStage
        - ApiKey
        - ApiUsagePlan
        Properties:
            KeyId: !Ref ApiKey
            KeyType: API_KEY
            UsagePlanId: !Ref ApiUsagePlan